### ISSUE TITLE
团队组建和管理功能

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#10]
团队是参与GAMEJAM和HAckson的基本单位，在一个合格的活动中会有比较完善的团队组织流程。比如GGJ会提前1个月的时间开始线上报名和拉群，在群里大家也会互相自我介绍并且在活动开始之前可能就已经完成了组队。组队不仅仅是因为开发需要，而且也是一种参与感的提现。当参与了多届活动之后，用户来到DAOJAM还可以回顾到过往每一次的组队情况。
## 功能说明

- [x] 项目在创建完成并添加流动金之后，别的DAOJAM用户在项目详情页中可点击“按钮”申请参与项目，在弹出的界面中填写联系方式和自我介绍后提交，创建者会收到通知邮件和站内提醒。
- [x] 创建者可 同意 或 拒绝 对方的申请，申请方同样会收到站内提醒。
- [x] 项目的创建者和参与者都会被展示在项目详情页里
- [x] 每个DAOJAM的注册用户都不限制申请和参与项目的数量。
- [x] 作为项目创建者，可以在项目管理页中主动添加参与者。项目所有参与者都会在完赛后会共同分享最终弄奖励，为防止过河拆桥现象，在成员加入 x 小时后将无法被创建者删除。

---
流程描述：
在项目页点击申请加入，弹窗填写信息后确认。创建者在通知中收到加入请求，点击确认后对方成为项目成员。在项目管理（原Fan票管理页）页中可以查看并删除已经添加的项目成员。同时创建者也可以在项目管理页中搜索并添加成员，对方会收到邀请通知，统一后即可加入项目。

**Comment by xiaotiandada** [comment]
按照原型处理 `可以在项目管理页中主动添加参与者` 和 `删除`

**Comment by xiaotiandada** [comment]
增加`邀请队员`的dialog
