### ISSUE TITLE
4月7号

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#102]
## 目标
将DAOJAM系统从以太坊平移到NEAR上
发布正式的PROJECT列表页和详情页
发布正式的项目创建流程

### 张翔

- [x] 基于NEAR的新手领取DaoT任务功能 （zx做好了，frank 不用做这个了）
  - [ ] 到时候正式版记得限制新手领取DaoT仅一次
- [x] 发布正式的Project列表页和详情页
- [x] 发布正式的项目创建流程
- [x] 发布基于NEAR的领票和投票功能

### 小田

- [x] 改进正式的Project详情页：
- 删除多余的交易和快速买币入口
- 按照设计稿重新刻画一下投票功能区
- [x] 改进投票功能：
- 遵循设计稿
- [x] 已选择的任务没有展示在项目详情页中
- [x] 调整PROJECT列表页面的DaoT图标
- [ ] 用户投票完成后，弹出文字提示“xxx 项目 得票 +10”

### Frank

- [x] 调整绑定要求为：仅需要NEAR登录
   - [x] 后端判断+前端提醒
![](https://user-images.githubusercontent.com/3261732/78631643-7f729300-78cf-11ea-9edf-fa954903b148.png)
   - [x] 非 Near 帐户绑定 Near 钱包
- [x] 修改服务器配置，引入了 NEAR 的钱包私钥用于合约交互
 
### 小音

- [x] 将新版的项目创建流程复制一份到 设置-->项目申请 页面中
文字调整需求：
- [x] 导航栏标签页stats改成leaderboard
- [x] 将STAT页面中的DAOS和DAO 全部改为 Projects 和 Project

### chauncey

- [x] 调整投票界面的样式，引入图标减少文字，简化按钮

## 今日测试
测试NEAR的登录、绑定、解绑、领票、投票 功能
测试新手任务功能
美化测试网的数据

**Comment by xiaotiandada** [comment]
调整PROJECT列表页面的DaoT图标

 图表换了 等待投票整理好后再修改一次8⃣️

**Comment by guanchao71** [comment]
奖励
绑定NEAR钱包后即可领取 100 DaoT
https://wallet.nearprotocol.com/

Reward
Gain 100 DaoT after binding NEAR wallet
https://wallet.nearprotocol.com/

---
你今日已花费 600 DaoT,投出了 46票
> 你每日可在同个项目上投票3次，最多不超过10票
> DaoT 和 票 是什么？（跳转到我的DaoT页面）

You have cost 600 DaoT，voted 46 ticket today
> You can voted at most 10 tickets & 3 times perday per project .
> What is DaoT and ticket？（跳转到我的DaoT页面）

---
你明日可领取 600 DaoT
> 每天可在导航栏中手动领取昨日投DaoT总量的1/3 + 20 DaoT

You can gain 600 DaoT tommorrow
> You can gain 1/3 DaoT of your voted yesterday + 20 a day.
