### ISSUE TITLE
个人主页中的VOTED页面开发

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#141]
#140 

用来展示这个用户曾经投票支持过的项目和投票记录
- [ ] 投票记录可以以收缩可展开的形式来展现总体投票记录和详细记录

**收缩展示：**
- [x] 项目logo、（点击进入项目页）
- [x] 项目名称、（点击进入项目页）
- [x] 投票总量、
- [x] DaoT消耗量
- [x] VOTE入口（进入项目页）

**展开展示：**
- [x] 投票时间、
- [x] 投票数量、
- [x] DaoT消耗量
- [x] NEAR链上入口

设计图已修改并上传至蓝湖。
![成员个人主页_投票](https://user-images.githubusercontent.com/51438318/78870150-43c6fd00-7a78-11ea-9612-e6344b5b78fe.png)

**Comment by xiaotiandada** [comment]
增加near地址

**Comment by xiaotiandada** [comment]
#168
