### ISSUE TITLE
增加项目的创建流程

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#16]
## 项目创建

- [ ] 在DAOs页面点击“创建项目”后会自动检测登录状态
- [ ] 点击后会弹窗要求支付“开通项目功能”的费用，使用投票券结算
- [ ] 支付的时候会检测用户是否完成绑定邮箱账号和Github账号的KYC任务，如果没有完成则无法创建项目
- [ ] 支付完成后直接引导前往“项目设置页面”

![image](https://user-images.githubusercontent.com/10827774/77268225-35d75500-6ce0-11ea-93e3-d742a3d30dce.png)

**Comment by xiaotiandada** [comment]
这个和 #4 重复了, 请写在一起或者分开 @guanchao71
