### ISSUE TITLE
Setting页面内容和结构调整

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#169]
## 侧边栏调整

- [x] MyDetail：包含原本的个人信息设置 &  账户设置（账户设置中仅包含 NEAR & Github）
- [x] VotePower：对等原先的My DaoT页面，删除页面中的大段简介内容（添加到导航栏菜单中）
- [x] VoteRecord：此页面没有调整
- [x] Invitation：此页面没有调整，但是受限于工作量，此页面和功能可能会被砍掉
- [x] ProjectSetting：将原先的Task、ProjectSetting、直播设置 合并在同一个页面中
- [x] CreateProject：这是一个独立的界面，只可以咋初次创建项目的时候访问，提交项目后就只能进入ProjectSetting页面了

## ProjectSetting

- [x] 增加Milestone设置：添加结构类似Website，添加的每一条都可以勾选check，可无限添加条目
- [x] 增加GallarySetting：暂时支持添加5张图片，添加的图片会在项目详情页面中展示
- [x] 必填项：PRIZE选择、LOGO、名称、封面图片、简介
- [x] 简介和介绍是两个不同的内容

![image](https://user-images.githubusercontent.com/10827774/79088744-10d18180-7d76-11ea-8239-290a159b3120.png)

**Comment by shellteo** [comment]
我来弄
