### ISSUE TITLE
修改项目设置的结构和条目

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#17]
### 任务选择

- [ ] 任务选择的入口在 菜单-->任务选择里
- [ ] DAOJAM活动会提供多个主线任务（主题）和支线任务（赞助任务），
- [ ] 创建者可以给自己的项目选择参与的任务，在最终提交之前都是可以修改的。
- [ ] 修改的结果会被反应在项目主页中。

![image](https://user-images.githubusercontent.com/10827774/77270135-f14eb800-6ce5-11ea-9df8-82360671dc04.png)

### 项目设置
在DAOJAM中，每个FAN票其实对应的是一个项目。相比于Matataki的区别在于将项目概念和Fan票分离了，但是表现形式上还是一体的。也就是说：一个DAOJAM项目 = 项目 + Fan票。

**Fan票 设置项**
- [ ] LOGO
- [ ] 名称
- [ ] 缩写（symbol）
- [ ] 发行量

**项目信息 设置项**

- [ ] 【新增】任务展示
- [ ] 【新增】封面图上传
- [ ] 【新增】项目名称
- [ ] 简介（对应原Fan票设置）
- [ ] 介绍（对应原Fan票设置）
- [ ] 【新增】项目REPO地址：此条会被展示在项目详情页的固定位置（项目概览）#18
- [ ] 【新增】成员管理：这里可以搜索添加成员，他人申请后加入的也会显示在这里。点击减号可以删除成员。（加入超过一定时间之后就无法删除此成员了#10）
- [ ] 相关网站
- [ ] 社交账号

![image](https://user-images.githubusercontent.com/10827774/77270153-00356a80-6ce6-11ea-8a4b-6cb91bf7378e.png)

### 开发动态
这是本次DAOJAM中新增加的内容，因为DAOJAM为完全线上开发大会，所以可能会出现评委们无法及时得知项目的进展，但是DAOJAM又十分依赖对项目开发状况的动态判断来做投票的决策。因此新增加了上传“开发动态”的功能。开发动态中包含“直播间” 和“开发动态”两个栏目
**直播间**

- [x] 可以添加任意数量的直播间链接
- [x] 创建者需要填写直播间地址和对应的开发者成员

**开发动态**

- [x] 可以添加任意数量的开发动态
- [x] 创建者需要填写标题和正文内容
- [x] 开发动态添加的时候按照倒序排列。

![image](https://user-images.githubusercontent.com/10827774/77270190-20652980-6ce6-11ea-801b-19d4654c138d.png)

**Comment by xiaotiandada** [comment]
【新增】项目REPO地址：此条会被展示在项目详情页的固定位置（项目概览）#18  在做这个

**Comment by xiaotiandada** [comment]
开发动态
这是本次DAOJAM中新增加的内容，因为DAOJAM为完全线上开发大会，所以可能会出现评委们无法及时得知项目的进展，但是DAOJAM又十分依赖对项目开发状况的动态判断来做投票的决策。因此新增加了上传“开发动态”的功能。开发动态中包含“直播间” 和“开发动态”两个栏目

**在做这个**

**Comment by xiaotiandada** [comment]
【新增】成员管理：这里可以搜索添加成员，他人申请后加入的也会显示在这里。点击减号可以删除成员。（加入超过一定时间之后就无法删除此成员了#10）

**在做**

**Comment by guanchao71** [comment]
结果：在DAOJAM这个阶段彻底抛弃以Fan票为骨架的项目结构，因此在设置项目的时候不存在发币行为，只需要填写项目的信息即可。
