### ISSUE TITLE
PROJECT详情页面 开发

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#18]
## 概述
项目详情页面被拆分为了多个模块，用来展示与项目相关的全部信息：
固定展示
- 项目概览
    - 投票功能

分标签页
- 项目信息
- 项目动态
- 项目支持

### 项目概览
**项目概览中包含了诸多的数据展示：**
- [x] 项目封面图
- [x] 项目LOGO
- [x] 项目创建者：点击后跳转个人主页
- [x] 项目REPO入口：点击后打开链接
- [x] 项目链上入口：点击后打开链接
- [x] 项目简介
- [x] 设置入口：仅创建者可见，点击后前往项目信息设置页
- [x] 分享入口：支持分享为widget #38，分享为邀请链接
- [x] 申请参与项目入口：对应申请加入项目流程#10
- [ ] 社交媒体入口：原本显示在“信息”标签页中的社交媒体

**以及关键数据**
- [x] 支持者数量
- [x] 投票数量
    - [ ] ~~用进度条显示我投票占百分比，鼠标指向会弹出文字描述~~
- [ ] ~~得分数~~
    - [ ] ~~用进度条显示我的影响占百分比，鼠标指向会弹出文字描述~~
- [ ] ~~项目排名：点击排名后前往STAT页面，查看排行榜~~

**以及投票功能 #35**
- [ ] ~~今日已投票数量~~
- [ ] ~~投1票按钮~~
- [ ] ~~投5票按钮~~
- [ ] ~~投最高按钮：点击后按照限制范围内最大可投数量投票~~
- [ ] 投自定义按钮：输入数量后进行投票，超过限额会提示超额
- [ ] 在投票框旁边会展示当前投票需要消耗的DaoT数量

-概览界面-
![image](https://user-images.githubusercontent.com/10827774/77271764-76d46700-6cea-11ea-901a-1504f10c30cc.png)

-概览中关键数据交互细节-
![image](https://user-images.githubusercontent.com/10827774/77271885-cfa3ff80-6cea-11ea-81d1-0d6bca8d97b7.png)

### 【分页】项目信息
包含内容有：
- [x] 项目介绍
- [ ] 团队成员
- [ ] 项目主题
- [ ] 相关网站
- [ ] 成就信息？
![image](https://user-images.githubusercontent.com/10827774/77272630-a2585100-6cec-11ea-90a7-14829a0bcde8.png)

### 【分页】项目动态
包含内容有
- [ ] 直播地址展示
- [ ] 开发动态文本展示
![image](https://user-images.githubusercontent.com/10827774/77272536-75a43980-6cec-11ea-8b12-324505152d2e.png)

### 【分页】项目支持
包含内容有
- [ ] 支持者列表
- [ ] 项目被投票流水记录
- [ ] 项目投票记录折线图
![image](https://user-images.githubusercontent.com/10827774/77272547-7b018400-6cec-11ea-943b-44319be15e20.png)

**Comment by xiaotiandada** [comment]
界面已经有了 只差核对功能和界面了
