### ISSUE TITLE
项目页内评论功能

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#249]
- [x] 项目评论查看、添加和删除的API https://github.com/DAOJAM/DAOJAM-BE/pull/67 https://github.com/DAOJAM/DAOJAM-BE/pull/68

以下功能都在 #252 实现
- [x] 前端显示项目评论
- [x] 前端可以发表评论
- [x] 用户可以删除自己的评论

**Comment by frankwei98** [comment]
评论的数据库结构
```sql
CREATE TABLE `project_comments` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '评论ID',
  `uid` int(11) DEFAULT NULL COMMENT '评论者UID',
  `projectId` int(11) DEFAULT NULL COMMENT '项目的ID',
  `createdAt` timestamp NULL DEFAULT NULL,
  `content` text COLLATE utf8mb4_bin COMMENT '评论的内容',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

**Comment by frankwei98** [comment]
进展：可以显示评论了 
还差评论发布、评论删除没实现
![image](https://user-images.githubusercontent.com/3261732/79964787-c78fd900-84bd-11ea-97a7-a5d9896df1ca.png)

**Comment by frankwei98** [comment]
功能好了
<img width="703" alt="image" src="https://user-images.githubusercontent.com/3261732/79978655-d765e800-84d2-11ea-8299-c7ba064c1f35.png">
