### ISSUE TITLE
完成 项目列表页面 的界面和功能开发

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#4]
在项目列表页面中包含全部在DAOJAM中创建的项目，此页面对应了导航栏上的DAOs入口。
页面中包含有的功能有：排序、筛选、搜索、项目列表、项目创建入口。下面将对其做注意说明
## 项目列表
- [ ] 项目列表默认按照流动金总量排序
- [ ] 项目列表展示DAOJAM中所有已经添加过流动金的项目卡片

项目卡片中包含有：
- [x] 项目封面图
- [x] Fan票LOGO
- [x] 项目名称
- [x] 项目简介
- [x] Fan票缩写
- [x] 支持者数量
- [x] 流动金总量
- [x] Fan票发行量

## 排序
排序需要支持以下方式的正序和降序：

- [ ] 按照支持者总量进行排序
- [ ] 按照总得票量进行排序
- [ ] 按照得分进行排序

## 筛选

- [ ] 按照全部项目进行筛选
- [ ] 按照只看星标进行筛选
- [ ] 按照只看我支持的进行筛选（登录后才可使用）

## 搜索

- [ ] 按照搜索结果对项目列表进行筛选

## 项目创建 #16
点击后会自动检测登录状态
点击后会弹窗要求支付“开通项目功能”的费用，使用投票券结算
如果没有绑定邮箱账号和Github账号则无法登录
支付完成后直接引导前往“项目设置页面”
![image](https://user-images.githubusercontent.com/10827774/77273323-3bd43280-6cee-11ea-9a3f-49afa2dcb337.png)

**Comment by xiaotiandada** [comment]
暂时只做了界面, 需要实际的内容才方便对接
