### ISSUE TITLE
新增Leadboard（排行榜和数据）页面

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#43]
在这个页面中展示整站的数据信息
**全站投票折线图**

- [ ] 今日
- [ ] 本周

**用户排行榜**：投票总量

- [ ] 今日
- [ ] 本周

**项目排行榜**：得票总量

- [ ] 今日
- [ ] 本周

![image](https://user-images.githubusercontent.com/10827774/77275078-5ad4c380-6cf2-11ea-8d98-d2f083408c28.png)

**Comment by LittleSound** [comment]
https://github.com/DAOJAM/DAO_Jam/pull/67
