### ISSUE TITLE
新增TASKS（任务）页面

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#44]
此页面比较适合直接嵌入在首页中，需要设计再次加工一下。
此页面是用来展示DAOJAM中所包含的任务选项
![image](https://user-images.githubusercontent.com/10827774/77275138-88ba0800-6cf2-11ea-95a0-2f7207604a84.png)

**Comment by LittleSound** [comment]
https://github.com/DAOJAM/DAO_Jam/issues/44
