### ISSUE TITLE
将DAOJAM部署到daojam.io这个域名上作为正式网

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#5]
- [x] daojam.io 注册 by Frank
- [x] DAOJAM 前端部署到daojam.io这个域名上
- [ ] DAOJAM 后端部署到backend.production.daojam.io这个域名上

**Comment by frankwei98** [comment]
动态更新：
DAOJam.io 前端已经可以自动部署了
![image](https://user-images.githubusercontent.com/3261732/77511549-43d9d100-6eac-11ea-803f-7a6818b550e3.png)

**Comment by frankwei98** [comment]
DAOJAM 后端已经可以自动部署到backend.production.daojam.io这个域名上
![image](https://user-images.githubusercontent.com/3261732/77513955-e5fbb800-6eb0-11ea-88c4-59fea7178895.png)
