### ISSUE TITLE
4月3号

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#91]
## 小田
- [x] 在Projects卡片上展示3个数据“参与人数”“得票数”“DaoT数”
- [ ] 在STAT页面中按照项目的3个数据接入，并且按照“用户（月/周）”和“项目（月/周）”进行排序
- [x] 在项目的详情页面中，删除Fan票的“交易”“快捷购买”入口
- [x] 在设置页面中，当用户没有申请过Project的时候不显示项目相关的3页设置#78
- [x] 刻画项目详情页面中的投票和操作区域界面
- [x] 在设置中增加任务选择功能
- [ ] 在个人主页中的DAOS页面中“我创建的DAO”内容点击后会404

## 张翔

- [x] 项目创建
- [x] NEAR

## 小音

- [x] 导航栏上的Project-->PROJECTS
- [x] 设置页面中将“DAO SETTING”更换为“ PROJECT SETTING”
- [x] 设置页面中，按照设计稿样式和 #79 里的文字刻画“我的DaoT页面”
- [x] ![image](https://user-images.githubusercontent.com/10827774/78353872-68852580-75dd-11ea-9861-b2ba6057f9fd.png)将图中红框部分改为“DaoT”
- [x] 删除 “我的投票” 页面中 “持有的流动金” ；将标题改为“我支持”
- [x] 将设置页中的表格改为紫色（非白色）

**Comment by xiaotiandada** [comment]
**正在做**

**Comment by xiaotiandada** [comment]
已改
``这块文字调整下--> Create New Project（Need 100 DaoT）``

**Comment by guanchao71** [comment]
![image](https://user-images.githubusercontent.com/10827774/78377063-b7dd4d00-7601-11ea-970a-b6aa163f5615.png)

- [ ] 红框部分的文字替换为“Projects”
